# Generated by Django 4.1 on 2022-11-18 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dia_nombre', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('hito_id', models.AutoField(primary_key=True, serialize=False)),
                ('hito_actividad', models.TextField(blank=True, null=True)),
                ('hito_docencia', models.TextField(blank=True, null=True)),
                ('hito_reglamentario', models.TextField(blank=True, null=True)),
                ('hito_fecha_inicio', models.DateField(blank=True, null=True)),
                ('hito_fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicacionPy',
            fields=[
                ('publ_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publ_nombre', models.CharField(max_length=45)),
                ('publ_descripcion', models.CharField(max_length=45)),
                ('publ_ubicacion', models.CharField(max_length=45)),
                ('publ_precio', models.CharField(max_length=45)),
                ('publ_creacion', models.CharField(max_length=45)),
                ('publ_stock', models.CharField(max_length=45)),
                ('publ_visibilidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publicacion_py',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('sede_id', models.AutoField(primary_key=True, serialize=False)),
                ('sede_nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('tall_id', models.AutoField(primary_key=True, serialize=False)),
                ('tall_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('tall_profesor', models.CharField(blank=True, max_length=45, null=True)),
                ('tall_descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('tall_cupo_act', models.IntegerField(blank=True, null=True)),
                ('tall_cupo_max', models.IntegerField(blank=True, null=True)),
                ('tall_estado', models.IntegerField(blank=True, null=True)),
                ('tall_ubicacion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tipo_usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tu_nombre', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_rut', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('usu_apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('usu_correo', models.CharField(blank=True, max_length=45, null=True)),
                ('usu_contrasena', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaTaller',
            fields=[
                ('dia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vidaSansana.dia')),
                ('dt_hora_incio', models.CharField(blank=True, max_length=6, null=True)),
                ('dt_hora_fin', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'dia_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HitoSede',
            fields=[
                ('hito', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vidaSansana.hito')),
            ],
            options={
                'db_table': 'hito_sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallUsuario',
            fields=[
                ('usu_rut', models.OneToOneField(db_column='usu_rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vidaSansana.usuario')),
            ],
            options={
                'db_table': 'tall_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPubl',
            fields=[
                ('usu_rut', models.OneToOneField(db_column='usu_rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vidaSansana.usuario')),
            ],
            options={
                'db_table': 'usuario_publ',
                'managed': False,
            },
        ),
    ]
