# Generated by Django 4.1.3 on 2022-11-15 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sede',
            fields=[
                ('sede_id', models.AutoField(primary_key=True, serialize=False)),
                ('sede_nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='new_table',
            fields=[
                ('tall_id', models.AutoField(primary_key=True, serialize=False)),
                ('tall_nombre', models.CharField(max_length=45)),
                ('tall_profesor', models.CharField(max_length=45)),
                ('tall_descripcion', models.CharField(max_length=45)),
                ('tall_cupo_act', models.IntegerField()),
                ('tall_cupo_max', models.IntegerField()),
                ('tall_estado', models.BinaryField()),
                ('tall_ubicacion', models.CharField(max_length=45)),
                ('sede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidaSansana.sede')),
            ],
        ),
    ]
