# Generated by Django 4.1.3 on 2022-11-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidaSansana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('puntuacion', models.IntegerField()),
                ('id_puntuacion', models.AutoField(primary_key=True, serialize=False)),
                ('publ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidaSansana.publicacionpy')),
                ('usu_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidaSansana.usuario')),
            ],
            options={
                'db_table': 'puntuacion',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario', models.TextField(blank=True, null=True)),
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('publ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidaSansana.publicacionpy')),
                ('usu_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidaSansana.usuario')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
