# Generated by Django 4.1.3 on 2022-11-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidaSansana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario', models.TextField(blank=True, null=True)),
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('puntuacion', models.IntegerField()),
                ('id_puntuacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Puntuacion',
                'managed': False,
            },
        ),
    ]
