# Generated by Django 4.1.3 on 2022-11-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidaSansana', '0002_comentario_puntuacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='puntuacion',
            options={},
        ),
    ]
